# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import latex_ocr_pb2 as latex__ocr__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in latex_ocr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LatexOCRStub(object):
    """Interface exported by the server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateLatex = channel.unary_unary(
                '/latexocr.LatexOCR/GenerateLatex',
                request_serializer=latex__ocr__pb2.LatexRequest.SerializeToString,
                response_deserializer=latex__ocr__pb2.LatexReply.FromString,
                _registered_method=True)
        self.GenerateLatexBytes = channel.unary_unary(
                '/latexocr.LatexOCR/GenerateLatexBytes',
                request_serializer=latex__ocr__pb2.LatexRequestBytes.SerializeToString,
                response_deserializer=latex__ocr__pb2.LatexReply.FromString,
                _registered_method=True)
        self.IsReady = channel.unary_unary(
                '/latexocr.LatexOCR/IsReady',
                request_serializer=latex__ocr__pb2.Empty.SerializeToString,
                response_deserializer=latex__ocr__pb2.ServerIsReadyReply.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/latexocr.LatexOCR/GetConfig',
                request_serializer=latex__ocr__pb2.Empty.SerializeToString,
                response_deserializer=latex__ocr__pb2.ServerConfig.FromString,
                _registered_method=True)


class LatexOCRServicer(object):
    """Interface exported by the server
    """

    def GenerateLatex(self, request, context):
        """Generate the latex code for a given image filepath
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateLatexBytes(self, request, context):
        """Generate the latex code for a given image in bytes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsReady(self, request, context):
        """Check if the server is ready to return requests
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Get the server config
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LatexOCRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateLatex': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLatex,
                    request_deserializer=latex__ocr__pb2.LatexRequest.FromString,
                    response_serializer=latex__ocr__pb2.LatexReply.SerializeToString,
            ),
            'GenerateLatexBytes': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLatexBytes,
                    request_deserializer=latex__ocr__pb2.LatexRequestBytes.FromString,
                    response_serializer=latex__ocr__pb2.LatexReply.SerializeToString,
            ),
            'IsReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsReady,
                    request_deserializer=latex__ocr__pb2.Empty.FromString,
                    response_serializer=latex__ocr__pb2.ServerIsReadyReply.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=latex__ocr__pb2.Empty.FromString,
                    response_serializer=latex__ocr__pb2.ServerConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'latexocr.LatexOCR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('latexocr.LatexOCR', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LatexOCR(object):
    """Interface exported by the server
    """

    @staticmethod
    def GenerateLatex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/latexocr.LatexOCR/GenerateLatex',
            latex__ocr__pb2.LatexRequest.SerializeToString,
            latex__ocr__pb2.LatexReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateLatexBytes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/latexocr.LatexOCR/GenerateLatexBytes',
            latex__ocr__pb2.LatexRequestBytes.SerializeToString,
            latex__ocr__pb2.LatexReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/latexocr.LatexOCR/IsReady',
            latex__ocr__pb2.Empty.SerializeToString,
            latex__ocr__pb2.ServerIsReadyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/latexocr.LatexOCR/GetConfig',
            latex__ocr__pb2.Empty.SerializeToString,
            latex__ocr__pb2.ServerConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
